import { LcdData, ConnectionType, ParallelPins, PixelGrid } from '../types';

const isCharEmpty = (char: PixelGrid): boolean => {
  return char.every(row => row.every(pixel => !pixel));
};

const charToBytes = (char: PixelGrid): string[] => {
  return char.map(row => {
    const binStr = row.map(pixel => (pixel ? '1' : '0')).join('');
    return `  B${binStr}`;
  });
};

const arraysEqual = (a: PixelGrid, b: PixelGrid): boolean => {
  for (let r = 0; r < 8; r++) {
    for (let c = 0; c < 5; c++) {
      if (a[r][c] !== b[r][c]) return false;
    }
  }
  return true;
};

export const generateArduinoCode = (
  lcdData: LcdData,
  connectionType: ConnectionType,
  i2cAddress: string,
  parallelPins: ParallelPins,
  projectName: string,
  animationType: string = 'none',
  animationDelay: number = 500
): string => {
  // Extract unique non-empty characters
  const uniqueChars: { data: PixelGrid; indices: number[] }[] = [];
  
  lcdData.forEach((char, index) => {
    if (isCharEmpty(char)) return;
    const existing = uniqueChars.find(uc => arraysEqual(uc.data, char));
    if (existing) {
      existing.indices.push(index);
    } else {
      uniqueChars.push({ data: char, indices: [index] });
    }
  });

  const uniqueCount = uniqueChars.length;
  const isDynamic = uniqueCount > 8;

  let code = `// Project: ${projectName}\n// Code generated by Embedded EG\n// Embedded EG — LCD 16×2 Pixel Designer\n// Custom Character Count: ${uniqueCount} (Max simultaneous is 8)\n\n`;

  if (connectionType === 'I2C') {
    code += `#include <Wire.h>\n#include <LiquidCrystal_I2C.h>\n\n`;
    code += `// Set the LCD address to ${i2cAddress} for a 16 chars and 2 line display\n`;
    code += `LiquidCrystal_I2C lcd(${i2cAddress}, 16, 2);\n\n`;
  } else {
    code += `#include <LiquidCrystal.h>\n\n`;
    code += `// Initialize the library by associating any needed LCD interface pin\n`;
    code += `// with the arduino pin number it is connected to\n`;
    code += `const int rs = ${parallelPins.rs}, en = ${parallelPins.en}, d4 = ${parallelPins.d4}, d5 = ${parallelPins.d5}, d6 = ${parallelPins.d6}, d7 = ${parallelPins.d7};\n`;
    code += `LiquidCrystal lcd(rs, en, d4, d5, d6, d7);\n\n`;
  }

  // Generate character byte arrays
  uniqueChars.forEach((uc, index) => {
    code += `byte customChar${index}[8] = {\n`;
    code += charToBytes(uc.data).join(',\n');
    code += `\n};\n\n`;
  });

  code += `void setup() {\n`;
  if (connectionType === 'I2C') {
    code += `  lcd.init();\n`;
    code += `  lcd.backlight();\n`;
  } else {
    code += `  lcd.begin(16, 2);\n`;
  }

  if (isDynamic) {
    code += `\n  // Note: Your design has more than 8 unique characters.\n`;
    code += `  // The Arduino LCD can only store 8 custom characters at a time.\n`;
    code += `  // To display them all, we will dynamically load and print them in the loop.\n`;
  } else {
    code += `\n  // Load custom characters into CGRAM\n`;
    uniqueChars.forEach((uc, index) => {
      code += `  lcd.createChar(${index}, customChar${index});\n`;
    });
    
    code += `\n  // Print the initial layout\n`;
    code += `  printLayout();\n`;
  }

  code += `}\n\n`;

  code += `void loop() {\n`;
  if (isDynamic) {
    code += `  // Sequential rendering due to >8 custom characters\n`;
    
    // Group characters into batches of 8
    for (let i = 0; i < uniqueChars.length; i += 8) {
      const batch = uniqueChars.slice(i, i + 8);
      code += `\n  // Batch ${Math.floor(i / 8) + 1}\n`;
      batch.forEach((uc, batchIndex) => {
        const globalIndex = i + batchIndex;
        code += `  lcd.createChar(${batchIndex}, customChar${globalIndex});\n`;
      });
      
      batch.forEach((uc, batchIndex) => {
        uc.indices.forEach(lcdPos => {
          const row = lcdPos < 16 ? 0 : 1;
          const col = lcdPos % 16;
          code += `  lcd.setCursor(${col}, ${row});\n`;
          code += `  lcd.write(byte(${batchIndex}));\n`;
          if (animationType === 'progressive') {
            code += `  delay(${animationDelay});\n`;
          }
        });
      });
      if (i + 8 < uniqueChars.length) {
        if (animationType !== 'progressive') {
          code += `  delay(500); // Small delay before loading next batch\n`;
        }
      }
    }
    code += `  delay(2000);\n`; // Loop delay
  } else {
    if (animationType === 'none') {
      code += `  // Static design, nothing needed in loop.\n`;
    } else if (animationType === 'blink') {
      code += `  lcd.noDisplay();\n`;
      code += `  delay(${animationDelay});\n`;
      code += `  lcd.display();\n`;
      code += `  delay(${animationDelay});\n`;
    } else if (animationType === 'scrollLeft') {
      code += `  lcd.scrollDisplayLeft();\n`;
      code += `  delay(${animationDelay});\n`;
    } else if (animationType === 'scrollRight') {
      code += `  lcd.scrollDisplayRight();\n`;
      code += `  delay(${animationDelay});\n`;
    } else if (animationType === 'progressive') {
      code += `  // Progressive draw is handled in setup() for static designs.\n`;
    }
  }
  code += `}\n\n`;

  if (!isDynamic) {
    code += `void printLayout() {\n`;
    
    if (animationType === 'progressive') {
       code += `  lcd.clear();\n`;
    }

    // Sort all print commands by position to make progressive draw look left-to-right, top-to-bottom
    const allPrints: { pos: number; cmd: string }[] = [];
    uniqueChars.forEach((uc, index) => {
      uc.indices.forEach(lcdPos => {
        const row = lcdPos < 16 ? 0 : 1;
        const col = lcdPos % 16;
        const cmd = `  lcd.setCursor(${col}, ${row});\n  lcd.write(byte(${index}));\n`;
        allPrints.push({ pos: lcdPos, cmd });
      });
    });

    allPrints.sort((a, b) => a.pos - b.pos);

    allPrints.forEach(p => {
      code += p.cmd;
      if (animationType === 'progressive') {
        code += `  delay(${animationDelay});\n`;
      }
    });

    code += `}\n`;
  }

  return code;
};
